import { DuaItem } from "./types";

export const quranicDuas: DuaItem[] = [
    // --- Group 1: النبي محمد ﷺ ---
    {
        id: "q_m_1",
        category: "quranic",
        arabic: "رَّبِّ أَدْخِلْنِي مُدْخَلَ صِدْقٍ وَأَخْرِجْنِي مُخْرَجَ صِدْقٍ وَاجْعَل لِّي مِن لَّدُنكَ سُلْطَانًا nَّصِيرًا",
        translation: "My Lord, cause me to enter a sound entrance and to exit a sound exit and grant me from Yourself a supporting authority.",
        transliteration: "Rabbi adkhilni mudkhala sidqin wa akhrijni mukhraja sidqin waj'al li min ladunka sultanan nasira.",
        source: "Al-Isra: 80",
        speaker: "النبي محمد ﷺ",
        context: "أمر إلهي بالدعاء عند الهجرة أو دخول مكة"
    },
    {
        id: "q_m_2",
        category: "quranic",
        arabic: "رَّبِّ اغْفِرْ وَارْحَمْ وَأَنتَ خَيْرُ الرَّاحِمِينَ",
        translation: "My Lord, forgive and have mercy, and You are the best of the merciful.",
        transliteration: "Rabbighfir warham wa Anta khayrur-rahimin.",
        source: "Al-Mu'minun: 118",
        speaker: "النبي محمد ﷺ",
        context: "أمر إلهي بالنهاية بالاستغفار والرحمة"
    },
    {
        id: 49,
        category: "quranic",
        arabic: "وَجَعَلْنَا مِن بَيْنِ أَيْدِيهِمْ سَدًّا وَمِنْ خَلْفِهِمْ سَدًّا فَأَغْشَيْنَاهُمْ فَهُمْ لَا يُبْصِرُونَ",
        translation: "And We have put before them a barrier and behind them a barrier and covered them, so they do not see.",
        transliteration: "Wa ja'alna mim bayni aydihim saddan wa min khalfihim saddan fa aghshaynahum fahum la yubsirun",
        source: "Surah Yasin (36:9)",
        speaker: "النبي محمد ﷺ",
        context: "عند الهجرة وخروجه من بيته أمام المشركين"
    },

    // --- Group 2: الأنبياء عليهم السلام ---
    // آدم وحواء
    {
        id: 17,
        category: "quranic",
        arabic: "رَبَّنَا ظَلَمْنَا أَنفُسَنَا وَإِن لَّمْ تَغْفِرْ لَنَا وَتَرْحَمْنَا لَنَكُونَنَّ مِنَ الْخَاسِرِينَ",
        translation: "Our Lord, we have wronged ourselves, and if You do not forgive us and have mercy upon us, we will surely be among the losers.",
        transliteration: "Rabbana zalamna anfusana wa in lam taghfir lana wa tarhamna lanakunanna minal-khasirin.",
        source: "Al-A'raf: 23",
        speaker: "آدم وحواء عليهما السلام",
        context: "بعد الأكل من الشجرة",
    },
    // نوح
    {
        id: 21,
        category: "quranic",
        arabic: "رَبِّ إِنِّي أَعُوذُ بِكَ أَنْ أَسْأَلَكَ مَا لَيْسَ لِي بِهِ عِلْمٌ ۖ وَإِلاَّ تَغْفِرْ لِي وَتَرْحَمْنِي أَكُن مِّنَ الْخَاسِرِينَ",
        translation: "My Lord, indeed I seek refuge in You from asking You that of which I have no knowledge. And unless You forgive me and have mercy upon me, I will be among the losers.",
        transliteration: "Rabbi inni a'udhu bika an as'alaka ma laysa li bihi 'ilm. Wa illa taghfir li wa tarhamni akun minal-khasirin.",
        source: "Hud: 47",
        speaker: "نوح عليه السلام",
        context: "بعد غرق ابنه العاق",
    },
    {
        id: 47,
        category: "quranic",
        arabic: "رَّبِّ لَا تَذَرْ عَلَى الْأَرْضِ مِنَ الْكَافِرِينَ دَيَّارًا * إِنَّكَ إِن تَذَرْهُمْ يُضِلُّوا عِبَادَكَ وَلَا يَلِدُوا إِلَّا فَاجِرًا كَفَّارًا",
        translation: "My Lord, do not leave upon the earth from among the disbelievers an inhabitant. Indeed, if You leave them, they will mislead Your servants and not beget except [every] wicked one and disbeliever.",
        transliteration: "Rabbi la tadhar 'alal-ardi minal-kafirina dayyara. Innaka in tadharhum yudillu 'ibadaka wa la yalidu illa fajiran kaffara.",
        source: "Nuh: 26-27",
        speaker: "نوح عليه السلام",
        context: "الدعاء على قومه الكافرين بعد اليأس منهم",
    },
    // إبراهيم وإسماعيل
    {
        id: 1,
        category: "quranic",
        arabic: "رَبَّنَا تَقَبَّلْ مِنَّا ۖ إِنَّكَ أَنتَ السَّمِيعُ الْعَلِيمُ * وَتُبْ عَلَيْنَا ۖ إِنَّكَ أَنتَ التَّوَّابُ الرَّحِيمُ",
        translation: "Our Lord, accept [this] from us. Indeed You are the Hearing, the Knowing. And accept our repentance. Indeed, You are the Accepting of repentance, the Merciful.",
        transliteration: "Rabbana taqabbal minna innaka Antas-Sami'ul-'Alim. Wa tub 'alayna innaka Antat-Tawwabur-Rahim.",
        source: "Al-Baqarah: 127-128",
        speaker: "إبراهيم وإسماعيل عليهما السلام",
        context: "عند بناء الكعبة",
    },
    {
        id: 24,
        category: "quranic",
        arabic: "رَبِّ اجْعَلْنِي مُقِيمَ الصَّلَاةِ وَمِن ذُرِّيَّتِي ۚ رَبَّنا وَتَقَبَّلْ دُعَاءِ * رَبَّنَا اغْفِرْ لِي وَلِوَالِدَيَّ وَلِلْمُؤْمِنِينَ يَوْمَ يَقُومُ الْحِسَابُ",
        translation: "My Lord, make me an establisher of prayer, and [many] from my descendants. Our Lord, and accept my supplication. Our Lord, forgive me and my parents and the believers the Day the account is established.",
        transliteration: "Rabbij'alni muqimas-salati wa min dhurriyyati Rabbana wa taqabbal du'a'. Rabbanaghfir li wa li-walidayya wa lil-mu'minina yawma yaqumul-hisab.",
        source: "Ibrahim: 40-41",
        speaker: "إبراهيم عليه السلام",
        context: "الدعاء لنفسه ولذريته والمسلمين",
    },
    {
        id: 36,
        category: "quranic",
        arabic: "رَبِّ هَبْ لِي حُكْمًا وَأَلْحِقْنِي بِالصَّالِحِينَ * وَاجْعَل لِّي لِسَانَ صِدْقٍ فِي الْآخِرِينَ * وَاجْعَلْنِي مِن وَرَثَةِ جَنَّةِ النَّعِيمِ * وَلَا تُخْزِنِي يَوْمَ يُبْعَثُونَ",
        translation: "My Lord, grant me authority and join me with the righteous. And grant me a reputation of honor among later generations. And place me among the inheritors of the Garden of Pleasure. And do not disgrace me on the Day they are [all] resurrected.",
        transliteration: "Rabbi hab li hukman wa alhiqni bis-salihin. Waj'al li lisana sidqin fil-akhirin. Waj'alni min warathati jannatin-na'im. Wa la tukhzini yawma yub'athun.",
        source: "Ash-Shu'ara: 83-87",
        speaker: "إبراهيم عليه السلام",
        context: "الدعاء بالحكمة والذكر الحسن",
    },
    {
        id: 50,
        category: "quranic",
        arabic: "إِنِّي ذَاهِبٌ إِلَىٰ رَبِّي سَيَهْدِينِ",
        translation: "I am going unto my Lord who will guide me.",
        transliteration: "Innee thaahibun ilaa rabbee sayahdeen",
        source: "Surah As-Saffat (37:99)",
        speaker: "إبراهيم عليه السلام",
        context: "عندما هاجر من قومه"
    },
    {
        id: 59,
        category: "quranic",
        arabic: "رَبِّ هَبْ لِي مِنَ الصَّالِحِينَ",
        translation: "My Lord, grant me [a child] from among the righteous.",
        transliteration: "Rabbi hab li minas-salihin.",
        source: "As-Saffat: 100",
        speaker: "إبراهيم عليه السلام",
        context: "دعاء لطلب الولد الصالح"
    },
    // يوسف
    {
        id: 22,
        category: "quranic",
        arabic: "رَبِّ أَنتَ وَلِيِّي فِي الدُّنْيَا وَالْآخِرَةِ ۖ تَوَفَّني مُسْلِمًا وَأَلْحِقْنِي بِالصَّالِحِينَ",
        translation: "You are my protector in this world and in the Hereafter. Cause me to die a Muslim and join me with the righteous.",
        transliteration: "Rabbi Anta waliyyi fid-dunya wal-akhirati tawaffani musliman wa alhiqni bis-salihin.",
        source: "Yusuf: 101",
        speaker: "يوسف عليه السلام",
        context: "بعد تحقيق رؤياه باجتماع شمله بأهله",
    },
    // أيوب
    {
        id: 30,
        category: "quranic",
        arabic: "أَنِّي مَسَّنِيَ الضُّرُّ وَأَنتَ أَرْحَمُ الرَّاحِمِينَ",
        translation: "Indeed, adversity has touched me, and you are the Most Merciful of the merciful.",
        transliteration: "Anni massaniyad-durru wa Anta Arhamur-Rahimin.",
        source: "Al-Anbiya: 83",
        speaker: "أيوب عليه السلام",
        context: "في مرضه وبلائه",
    },
    // موسى
    {
        id: 27,
        category: "quranic",
        arabic: "رَبِّ اشْرَحْ لِي صَدْرِي * وَيَسِّرْ لِي أَمْرِي * وَاحْلُلْ عُقْدَةً مِّن لِّسَانِي * يَفْقَهُوا قَوْلِي",
        translation: "My Lord, expand for me my breast [with assurance]. And ease for me my task. And untie the knot from my tongue. That they may understand my speech.",
        transliteration: "Rabbishrah li sadri. Wa yassir li amri. Wahlul 'uqdatan min lisani. Yafqahu qawli.",
        source: "Taha: 25-28",
        speaker: "موسى عليه السلام",
        context: "قبل مخاطبة فرعون",
    },
    {
        id: 55,
        category: "quranic",
        arabic: "وَأَدْخِلْنَا فِي رَحْمَتِكَ وَأَنْتَ أَرْحَمُ الرَّاحِمِينَ",
        translation: "And admit us into Your mercy, for You are the most merciful of the merciful.",
        transliteration: "Wa adkhilna fi rahmatika wa Anta Arhamur-Rahimin.",
        source: "Al-A'raf: 151",
        speaker: "موسى عليه السلام",
        context: "دعاء لنفسه ولأخيه هارون"
    },
    {
        id: 57,
        category: "quranic",
        arabic: "رَبِّ نَجِّنِي مِنَ الْقَوْمِ الظَّالِمِينَ",
        translation: "My Lord, save me from the wrongdoing people.",
        transliteration: "Rabbi najjini minal-qawmiz-zalimin.",
        source: "Al-Qasas: 21",
        speaker: "موسى عليه السلام",
        context: "حين خرج من مصر خائفاً يترقب"
    },
    {
        id: 58,
        category: "quranic",
        arabic: "رَبِّ إِنِّي لِمَا أَنْزَلْتَ إِلَيَّ مِنْ خَيْرٍ فَقِيرٌ",
        translation: "My Lord, indeed I am, for whatever good You would send down to me, in need.",
        transliteration: "Rabbi inni lima anzalta ilayya min khayrin faqir.",
        source: "Al-Qasas: 24",
        speaker: "موسى عليه السلام",
        context: "حين سقى لابنتي شعيب وتولى إلى الظل"
    },
    // هارون
    {
        id: 54,
        category: "quranic",
        arabic: "فَلَا تُشْمِتْ بِيَ الْأَعْدَاءَ وَلَا تَجْعَلْنِي مَعَ الْقَوْمِ الظَّالِمِينَ",
        translation: "So let not the enemies rejoice over me and do not place me among the wrongdoing people.",
        transliteration: "Fala tushmit biyal-a'da'a wa la taj'alni ma'al-qawmiz-zalimin.",
        source: "Al-A'raf: 150",
        speaker: "هارون عليه السلام",
        context: "حين خاطب موسى عليهما السلام"
    },
    // سليمان
    {
        id: 38,
        category: "quranic",
        arabic: "رَبِّ أَوْزِعْنِي أَنْ أَشْكُرَ نِعْمَتَكَ الَّتِي أَنْعَمْتَ عَلَيَّ وَعَلَىٰ وَالِدَيَّ وَأَنْ أَعْمَلَ صَالِحًا تَرْضَاهُ وَأَدْخِلْنِي بِرَحْمَتِكَ فِي عِبَادِكَ الصَّالِحِينَ",
        translation: "My Lord, enable me to be grateful for Your favor which You have bestowed upon me and upon my parents and to work righteousness of which You will approve and add me by Your mercy into [the ranks of] Your righteous servants.",
        transliteration: "Rabbi awzi'ni an ashkura ni'matakal-lati an'amta 'alayya wa 'ala walidayya wa an a'mala salihan tardahu wa adkhilni bi-rahmatika fi 'ibadikas-salihin.",
        source: "An-Naml: 19",
        speaker: "سليمان عليه السلام",
        context: "حين سمع النملة شكر النعمة",
    },
    // يونس
    {
        id: 28,
        category: "quranic",
        arabic: "لَّا إِلَٰهَ إِلَّا أَنتَ سُبْحَانَكَ إِنِّي كُنتُ مِنَ الظَّالِمِينَ",
        translation: "There is no deity except You; exalted are You. Indeed, I have been of the wrongdoers.",
        transliteration: "La ilaha illa Anta Subhanaka inni kuntu minaz-zalimin.",
        source: "Al-Anbiya: 87",
        speaker: "يونس عليه السلام",
        context: "في بطن الحوت",
    },
    // زكريا
    {
        id: 9,
        category: "quranic",
        arabic: "رَبِّ هَبْ لِي مِن لَّدُنكَ ذُرِّيَّةً ۖ إِنَّكَ سَمِيعُ الدُّعَاءِ",
        translation: "My Lord, grant me from Yourself a good offspring. Indeed, You are the Hearer of supplication.",
        transliteration: "Rabbi hab li min ladunka dhurriyyatan. Innaka Sami'ud-du'a'.",
        source: "Al Imran: 38",
        speaker: "زكريا عليه السلام",
        context: "دعاء لطلب الذرية",
    },
    {
        id: 29,
        category: "quranic",
        arabic: "رَبِّ لَا تَذَرْنِي فَرْدًا وَأَنتَ خَيْرُ الْوَارِثِينَ",
        translation: "My Lord, do not leave me alone [with no heir], while You are the best of inheritors.",
        transliteration: "Rabbi la tadharni fardan wa Anta khayrul-warithin.",
        source: "Al-Anbiya: 89",
        speaker: "زكريا عليه السلام",
        context: "طلب الولد والوارث الصالح",
    },
    // لوط
    {
        id: 37,
        category: "quranic",
        arabic: "رَبِّ نَجِّنِي وَأَهْلِي مِمَّا يَعْمَلُونَ",
        translation: "My Lord, save me and my family from what they do.",
        transliteration: "Rabbi najjini wa ahli mimma ya'malun.",
        source: "Ash-Shu'ara: 169",
        speaker: "لوط عليه السلام",
        context: "دعاء للنجاة من قومه",
    },
    // عيسى
    {
        id: 53,
        category: "quranic",
        arabic: "وَارْزُقْنَا وَأَنْتَ خَيْرُ الرَّازِقِينَ",
        translation: "And provide for us, and You are the best of providers.",
        transliteration: "Warzuqna wa Anta khayrur-raziqin.",
        source: "Al-Ma'idah: 114",
        speaker: "عيسى عليه السلام",
        context: "عند طلب المائدة من السماء"
    },

    // --- Group 3: الصالحون والمؤمنون والملائكة ---
    // الفاتحة (المسلمون)
    {
        id: 51,
        category: "quranic",
        arabic: "اهْدِنَا الصِّرَاطَ الْمُسْتَقِيمَ * صِرَاطَ الَّذِينَ أَنْعَمْتَ عَلَيْهِمْ غَيْرِ الْمَغْضُوبِ عَلَيْهِمْ وَلَا الضَّالِّينَ",
        translation: "Guide us to the straight path - The path of those upon whom You have bestowed favor, not of those who have evoked [Your] anger or of those who are astray.",
        transliteration: "Ihdinas-siratal-mustaqim. Siratal-ladhina an'amta 'alayhim ghayril-maghdubi 'alayhim walad-dallin.",
        source: "Al-Fatihah: 6-7",
        speaker: "المسلمون",
        context: "سورة الفاتحة - ركن الصلاة"
    },
    // المؤمنون
    {
        id: 2,
        category: "quranic",
        arabic: "رَبَّنَا آتِنَا فِي الدُّنْيَا حَسَنَةً وَفِي الْآخِرَةِ حَسَنَةً وَقِنَا عَذَابَ النَّارِ",
        translation: "Our Lord, give us in this world [that which is] good and in the Hereafter [that which is] good and protect us from the punishment of the Fire.",
        transliteration: "Rabbana atina fid-dunya hasanatan wa fil-akhirati hasanatan wa qina 'adhaban-nar.",
        source: "Al-Baqarah: 201",
        speaker: "المؤمنون",
        context: "دعاء جامع لخير الدنيا والآخرة",
    },
    {
        id: 3,
        category: "quranic",
        arabic: "رَبَّنَا أَفْرِغْ عَلَيْنَا صَبْرًا وَثَبِّتْ أَقْدَامَنَا وَانصُرْنَا عَلَى الْقَوْمِ الْكَافِرِينَ",
        translation: "Our Lord, pour upon us patience and plant firmly our feet and give us victory over the disbelieving people.",
        transliteration: "Rabbana afrigh 'alayna sabran wa thabbit aqdamana wansurna 'alal-qawmil-kafirin.",
        source: "Al-Baqarah: 250",
        speaker: "المؤمنون (قوم طالوت)",
        context: "عند عزمهم على القتال والمواجهة",
    },
    {
        id: 4,
        category: "quranic",
        arabic: "رَبَّنَا لَا تُؤَاخِذْنَا إِن نَّسِينَا أَوْ أَخْطَأْنَا ۚ رَبَّنَا وَلَا تَحْمِلْ عَلَيْنَا إِصْرًا كَمَا حَمَلْتَهُ عَلَى الَّذِينَ مِن قَبْلِنَا",
        translation: "Our Lord, do not impose blame upon us if we have forgotten or erred. Our Lord, and lay not upon us a burden like that which You laid upon those before us.",
        transliteration: "Rabbana la tu'akhidhna in nasina aw akhta'na. Rabbana wa la tahmil 'alayna isran kama hamaltahu 'alal-ladhina min qablina.",
        source: "Al-Baqarah: 286",
        speaker: "المؤمنون",
        context: "خواتيم سورة البقرة - الاستغفار وطلب التيسير",
    },
    {
        id: 5,
        category: "quranic",
        arabic: "رَبَّنَا وَلَا تُحَمِّلْنَا مَا لَا طَاقَةَ لَنَا بِهِ ۖ وَاعْفُ عَنَّا وَاغْفِرْ لَنَا وَارْحَمْنَا ۚ أَنتَ مَوْلَانَا فَانصُرْنَا عَلَى الْقَوْمِ الْكَافِرِينَ",
        translation: "Our Lord, and burden us not with that which we have no ability to bear. And pardon us; and forgive us; and have mercy upon us. You are our protector, so give us victory over the disbelieving people.",
        transliteration: "Rabbana wa la tuhammilna ma la taqata lana bihi wa'fu 'anna waghfir lana warhamna Anta mawlana fansurna 'alal-qawmil-kafirin.",
        source: "Al-Baqarah: 286",
        speaker: "المؤمنون",
        context: "خواتيم سورة البقرة - الدعاء بالرحمة والنصر",
    },
    {
        id: 6,
        category: "quranic",
        arabic: "رَبَّنَا لَا تُزِغْ قُلُوبَنَا بَعْدَ إِذْ هَدَيْتَنَا وَهَبْ لَنَا مِن لَّدُنكَ رَحْمَةً ۚ إِنَّكَ أَنتَ الْوَهَّابُ",
        translation: "Our Lord, let not our hearts deviate after You have guided us and grant us from Yourself mercy. Indeed, You are the Bestower.",
        transliteration: "Rabbana la tuzigh qulubana ba'da idh hadaytana wa hab lana min ladunka rahmatan innaka Antal-Wahhab.",
        source: "Al Imran: 8",
        speaker: "الراسخون في العلم",
        context: "الثبات على الحق",
    },
    {
        id: 7,
        category: "quranic",
        arabic: "رَبَّنَا إِنَّكَ جَامِعُ النَّاسِ لِيَوْمٍ لَّا رَيْبَ فِيهِ ۚ إِنَّ اللَّهَ لَا يُخْلِفُ الْمِيعَادَ",
        translation: "Our Lord, surely You will gather the people for a Day about which there is no doubt. Indeed, Allah does not fail in His promise.",
        transliteration: "Rabbana innaka jami'un-nas liyawmil-la rayba fih. Innallaha la yukhliful-mi'ad.",
        source: "Al Imran: 9",
        speaker: "الراسخون في العلم",
        context: "الإقرار باليوم الآخر",
    },
    {
        id: 8,
        category: "quranic",
        arabic: "رَبَّنَا إِنَّنَا آمَنَّا فَاغْفِرْ لَنَا ذُنُوبَنَا وَقِنَا عَذَابَ النَّارِ",
        translation: "Our Lord, indeed we have believed, so forgive us our sins and protect us from the punishment of the Fire.",
        transliteration: "Rabbana innana amanna faghfir lana dhunubana wa qina 'adhaban-nar.",
        source: "Al Imran: 16",
        speaker: "المؤمنون",
        context: "الدعاء بالمغفرة والوقاية من النار",
    },
    {
        id: 52,
        category: "quranic",
        arabic: "حَسْبُنَا اللَّهُ وَنِعْمَ الْوَكِيلُ",
        translation: "Sufficient for us is Allah, and [He is] the best Disposer of affairs.",
        transliteration: "Hasbunallahu wa ni'mal-wakil.",
        source: "Al Imran: 173",
        speaker: "المؤمنون",
        context: "عند الشدائد وتهديد الأعداء"
    },
    // الملائكة
    {
        id: 40,
        category: "quranic",
        arabic: "رَبَّنَا وَسِعْتَ كُلَّ شَيْءٍ رَحْمَةً وَعِلْمًا فَاغْفِرْ لِلَّذِينَ تَابُوا وَاتَّبَعُوا سَبِيلَكَ وَقِهِمْ عَذَابَ الْجَحِيمِ",
        translation: "Our Lord, You have encompassed all things in mercy and knowledge, so forgive those who have repented and followed Your way and protect them from the punishment of Hellfire.",
        transliteration: "Rabbana wasi'ta kulla shay'in rahmatan wa 'ilman faghfir lilladhina tabu wattaba'u sabilaka wa qihim 'adhabal-jahim.",
        source: "Ghafir: 7",
        speaker: "الملائكة حملة العرش",
        context: "يستغفرون للذين آمنوا",
    },
    // آسية
    {
        id: 46,
        category: "quranic",
        arabic: "رَبِّ ابْنِ لِي عِندَكَ بَيْتًا فِي الْجَنَّةِ وَنَجِّنِي مِنَ الْقَوْمِ الظَّالِمِينَ",
        translation: "My Lord, build for me near You a house in Paradise and save me from the wrongdoing people.",
        transliteration: "Rabbibni li 'indaka baytan fil-jannah wa najjini minal-qawmiz-zalimin.",
        source: "At-Tahrim: 11",
        speaker: "آسية امرأة فرعون",
        context: "عند تعذيبها وطلب النجاة والجنة",
    },
    // المؤمنون التابعون
    {
        id: 44,
        category: "quranic",
        arabic: "رَبَّنَا اغْفِرْ لَنَا وَلِإِخْوَانِنَا الَّذِينَ سَبَقُونَا بِالْإِيمَانِ وَلَا تَجْعَلْ فِي قُلُوبِنَا غِلًّا لِّلَّذِينَ آمَنُوا",
        translation: "Our Lord, forgive us and our brothers who preceded us in faith and put not in our hearts [any] resentment toward those who have believed.",
        transliteration: "Rabbanaghfir lana wa li-ikhwaninal-ladhina sabaquna bil-imani wa la taj'al fi qulubina ghillal-lilladhina amanu.",
        source: "Al-Hashr: 10",
        speaker: "المؤمنون التابعون",
        context: "دعاء للمهاجرين والأنصار ومن سبقوهم",
    },
    // الوالدين
    {
        id: 56,
        category: "quranic",
        arabic: "رَّبِّ ارْحَمْهُمَا كَمَا رَبَّيَانِي صَغِيرًا",
        translation: "My Lord, have mercy upon them as they brought me up [when I was] small.",
        transliteration: "Rabbir-hamhuma kama rabbayani saghira.",
        source: "Al-Isra: 24",
        speaker: "المسلم (للولد)",
        context: "الدعاء للوالدين"
    }
];
